package mapreduce

import (
	"hash/fnv"
	"io/ioutil"
	"os"
	"encoding/json"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).
	//

	contentsByte, _ := ioutil.ReadFile(inFile)
	contents := string(contentsByte)
	res := mapF(inFile, contents)
	// res 拆分成 nReduce 部分
	// segment := len(res) / nReduce
	// 把结果分为 nReduce 个部分，ihash 分别放到其中
	intermediates := make([]*os.File, nReduce)
	for i, _ := range intermediates {
		name := reduceName(jobName, mapTask, i)
		intermediates[i], _ = os.Create(name)
		defer intermediates[i].Close()
	}
	for _, kv := range res {
		index := ihash(kv.Key)
		encoder := json.NewEncoder(intermediates[index])
		encoder.Encode(kv)
	}
	// for r := 0; r < nReduce; r++ {
	// 	name := reduceName(jobName, mapTask, r)
	// 	var contentPart []KeyValue
	// 	// 每一对 kv 被 ; 分开
	// 	if r == nReduce - 1 {
	// 		contentPart = res[r * segment : ]
	// 	} else {
	// 		contentPart = res[r * segment :(r + 1) * segment]
	// 	}
	// 	file, _ := os.Create(name)

	// 	enc := json.NewEncoder(file)
	// 	for _, kv := range contentPart {
	// 		enc.Encode(kv)
	// 	}
	// }
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
